### ISSUE TITLE
kmflow_re1000_rs256.yml doesn't work

### ISSUE THREAD

**Issue by whw-alex** [BaratiLab/Diffusion-based-Fluid-Super-resolution#10]
Hi! I started directly from step 2 and ran `python main.py --config kmflow_re1000_rs256.yml --seed 1234 --sample_step 1 --t 240 --r 30` in the main directory of this repo, but got the following message:

Traceback (most recent call last):
  File "main.py", line 112, in <module>
    sys.exit(main())
  File "main.py", line 94, in main
    args, config, logger, log_dir = parse_args_and_config()
  File "main.py", line 40, in parse_args_and_config
    dir_name = 'recons_{}_t{}_r{}_lam{}'.format(config.data.data_kw,
AttributeError: 'Namespace' object has no attribute 'data_kw'

Can you please provide the scripts used in your experiments in order for me to reproduce the results?

**Comment by jhbastek** [comment]
Same issue here. It seems that there are a few things missing to get this script to actually run. If the authors could double-check this and make sure that the provided version runs, that would be greatly appreciated. From quickly glancing over the code, it seems like these are only minor issues.
Thanks in advance!

**Comment by lassychen** [comment]
I have the same problem as above,do you have solve?

**Comment by ManuBN786** [comment]
How did you solve this issue ?

**Comment by leonardung** [comment]
Some arguments in the config files are missing. 

For the model without physics-informed conditioning you need to add the following in the kmflow_re1000_rs256.yml:
 - data.data_dir : path to High resolution data
 - data.sample_data_dir : path to Low resolution data
 - data.data_kw: 'u3232'
 - data.smoothing: False
 - data.smoothing_scale: 5
 - sampling.dump_arr : True
 - sampling.log_loss: True

For the model with physics-informed conditioning you need to add the following in the kmflow_re1000_rs256_conditional.yml:
 - data.data_dir : path to High resolution data
 - data.sample_data_dir : path to Low resolution data
 - data.data_kw: 'u3232'
 - data.smoothing: True
 - data.smoothing_scale: 7
 - sampling.dump_arr : True
 - sampling.guidance_weight: 0.
 - sampling.dump_arr: True
 - sampling.log_loss: True
